// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMYea6ZRpm2xcnXXZUhJoGwofhaNfAbg',
    appId: '1:532247717709:web:7d7a95e3b3a88725393904',
    messagingSenderId: '532247717709',
    projectId: 'flut-trial',
    authDomain: 'flut-trial.firebaseapp.com',
    storageBucket: 'flut-trial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqfXe--8I8AH_Jss168QLRMK90DTgzHgY',
    appId: '1:532247717709:android:8d06389d54003b62393904',
    messagingSenderId: '532247717709',
    projectId: 'flut-trial',
    storageBucket: 'flut-trial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCiMqn5px3NbB3tt4VPAb4bG27967z7P0',
    appId: '1:532247717709:ios:b31fd43dde053c71393904',
    messagingSenderId: '532247717709',
    projectId: 'flut-trial',
    storageBucket: 'flut-trial.appspot.com',
    iosClientId: '532247717709-2j06ggn6hdsthp289igpg1s6eepg0rl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCiMqn5px3NbB3tt4VPAb4bG27967z7P0',
    appId: '1:532247717709:ios:b31fd43dde053c71393904',
    messagingSenderId: '532247717709',
    projectId: 'flut-trial',
    storageBucket: 'flut-trial.appspot.com',
    iosClientId: '532247717709-2j06ggn6hdsthp289igpg1s6eepg0rl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial',
  );
}
